### ISSUE TITLE
Revisit job trackers design

### ISSUE THREAD

**Issue by anarchivist** [pod4lib/aggregator#317]
During the MVP workcycle, we added job trackers to the dashboard so users could get insight into the status of their data as it gets processed. The current display, as reported by staff at Dartmouth, is leading to some confusion:

![Screen Shot 2021-02-23 at 2 21 18 PM](https://user-images.githubusercontent.com/73732/108916528-3f012e00-75e3-11eb-9131-02dcefa3e2c9.png)

We should probably revisit the design and intent for the job trackers, and think about how to accurately and succinctly convey whether files have been successfully processed.

**Comment by corylown** [comment]
@ggeisler as we discussed on Feb. 3 I'm adding some detail to this ticket about possible states that we might want to convey with the job tracker. This is somewhat of a guess on my part but should provide a starting point for an improved design:

- Job is actively processing normally.
- Job is stalled and may need attention.
- Job is in an error state/failed and needs attention.
- Job completed. (maybe the indicator goes away or remains displayed for a while in such a way that it indicates successful completion.)

**Comment by ggeisler** [comment]
@corylown Is there a way for me to see examples of a variety of processing output (to understand the range of data that is exposed, like names of different types of jobs, etc.) beyond just clicking through the different organizations in the app and seeing if their streams happen to processing output?

I can work on a rough design without that, but if a better source of examples exist it would be useful.

**Comment by corylown** [comment]
@ggeisler 

Job Tracker data:

job_class: `Marc Profiling Job`, `Extract Marc Record Metadata Job`
resource_label: `pod_220212_uni_06500000_06999999.marc `, `2022-02-13T17:40:14Z `
total: `0 to n`
progress: `0 to n`
created_at: `Sun, 06 Mar 2022 14:30:46.329333000 UTC +00:00`
updated_at: `Sun, 06 Mar 2022 14:30:46.329333000 UTC +00:00`

I think we might be able to use the date last updated to determine if a job is stale. And the total count being 0 or something else unexpected could indicate a problem with the job.

<img width="1349" alt="Screen Shot 2022-03-08 at 10 48 48 AM" src="https://user-images.githubusercontent.com/458247/157275171-9754432e-db7c-4f24-8a75-a4feec6b7f1b.png">

**Comment by ggeisler** [comment]
Below are some initial redesign ideas. There are two main things I think are worth focusing on now to move this forward:

- Is it technically feasible -- and does it seem better for the user -- to present the processing status info in table form, where I believe the user can scan the info easier to find out they're interested in?
- How can we best help the user find jobs of interest based on their job status (user wants to verify that a recent job has completed; user wants to see if any of their jobs have run into problems)?

There are probably also related policy questions to answer as part of this revision (e.g., how long do we show completed jobs?) but I'm ignoring those for now.

(Note that in the mockups below I've reused the same three jobs with different status; this is just to make doing mockups quicker, but obviously the same job would not actually appear with more than one type of status.)

## Presenting job status info in a table
Here's the basic table presentation, based on the job status metadata mentioned in earlier comments as likely available to us. I shortened the date fields considerably; this might be too much, but we have several date formats in use across the app and I think we need to standardize on one date display format before deciding exactly how these fields should look.

Also, it looks like we're currently intending to show a progress bar for each job; I've replaced that with an "x of y completed" column to keep things compact and because I think that provides the user with just as much value as a progress bar. But potentially we could display a progress bar as the second line of each row to replace the "x of y" column if we think that would be more helpful to users.

<img width="1214" alt="Screen Shot 2022-03-10 at 1 42 21 PM" src="https://user-images.githubusercontent.com/101482/157753009-a7a21b9d-758c-40a0-a443-218c88f38b2f.png">

## Presentation options
Assuming we replace the current processing status display with some form of the table above, there are some options for how we display it that I think are worth discussing. In the example above I'm assuming the table just replaces the current alert-box display. In that approach I've included a legend so the user can interpret the different status icons more quickly. But I think there are potentially other ways of displaying things that might be easier for the user.

### Separate processing status tables by type
This approach uses page headers to identify the different status possibilities and presents a table dedicated to each status class. (Not represented is what happens when there are no jobs in a given status class; we could just show a `There are no jobs that currently need attention.` type message in place of the table, for example.) The advantages of this approach are that the user could more quickly focus on a specific type of status they might be interested in and see what jobs match, and we wouldn't need to display a legend. The main disadvantage is it takes more space on the page than a consolidated table.

<img width="1214" alt="Screen Shot 2022-03-10 at 1 43 13 PM" src="https://user-images.githubusercontent.com/101482/157767707-7390c2f4-e8cc-4dbf-9314-b25b5998da98.png">


###  Separate processing status tables by type in an accordion component
This is the same idea as above, with the same advantages, but is more compact because only one status type is displayed at a time (at least by default). 

<img width="1214" alt="Screen Shot 2022-03-10 at 1 44 05 PM" src="https://user-images.githubusercontent.com/101482/157767735-184a99b6-5737-4ed2-85b1-48b8ebfd8e93.png">

---

<img width="1214" alt="Screen Shot 2022-03-10 at 1 44 31 PM" src="https://user-images.githubusercontent.com/101482/157767749-ab2bad87-40f5-4d9b-b509-06241da9cc5f.png">

---

<img width="1214" alt="Screen Shot 2022-03-10 at 1 44 51 PM" src="https://user-images.githubusercontent.com/101482/157767778-ddaab35e-3d3d-4e46-bd92-8fa7372e70c1.png">

**Comment by corylown** [comment]
I've spent some time digging into the `JobTracker` setup in the aggregator app and want to leave some breadcrumbs for myself or the next dev to look a this:

- JobTracker entries are cleared out once they succeed. If we want to show successful jobs entries we'll need to add some way to retain the entry for a period of time. Maybe instead of getting cleared out the status gets updated to `:success` and gets retained for a period of time.
- There's no way currently to know when a job is hanging out in the retry set, which more or less indicates something went awry but we're going to try again. I think it would be useful to display this state as `:stalled` as indicated in Gary's mock-ups.
- The same issue applies to jobs that have been sent to the dead set. Jobs in the dead zone should be marked as `:failed` in the UI.

## How to get better job state info

There may be a better way to do this, but here's a path forward:

- Store the `provider_job_id` (Sidekiq job) id in `JobTracker` in the `ApplicationJob` class, something like: 
```ruby
  def find_or_initialize_job_tracker
    JobTracker.find_or_create_by(job_id: job_id) do |tracker|
      tracker.provider_job_id = self.provider_job_id
  end
end
```

- Use the Sidekiq API in the JobTracker model to check whether a JobTracker instance is in either the retry or the dead set. something like:
```ruby
  def in_retry_set?
    retry_set = Sidekiq::RetrySet.new
    retry_set.select { |job| job.item['jid'] == self.provider_job_id }.any?
  end

  def in_dead_set?
    dead_set = Sidekiq::DeadSet.new
    dead_set.select { |job| job.item['jid'] == self.provider_job_id }.any?
  end
```

**Comment by JohnMarkOckerbloom** [comment]
There's a lot I like about @ggeisler's design.  What I think could be very useful is to always have a brief summary display at the top showing the number of jobs active, needing attention, and (recently) successful.  Right now, it looks like streams that have all jobs completed show no job summary at the top, but especially when the streams have a lot of files, it could be helpful to have a quick reminder of whether or not processing is "done" or not.

I expect that most of the time the "active" and "needs attention" counts would be 0, but seeing the 0s is itself a helpful cue, since it shows that everything's been processed successfully, more quickly than scrolling through a potentially long list of files would.  (An uploader creating a new stream, for instance, could use the 0s as a cue to go ahead and make the new stream default.)

I agree that any always-present jobs display should be compact by default.  The accordion design appears to be one way of doing that.  It might also be useful to color-code the numbers to quickly identify parts of the accordion that one might want to open.  (For example, one could use blue similar to the in-progress color for non-zero numbers of in-progress jobs, and yellow or red for non-zero numbers of jobs that need attention, while green could be used to show that all jobs are completed and/or there are no jobs needing attention.  But I leave it to the UX experts to determine what would work best for recognition and readability.  Likewise, they can figure out the best way to compactly display a progress bar if desired without taking up too much extra vertical real estate. One compact possibility, for instance, might be an underlining of the "x of y" numbers column, with the proportion of completed records represented as a dark underline and the proportion or remaining records represented as a light underline.) 

As part of this display, I agree that retaining a record of successfully complete jobs, at least for some period of time, would be useful, as @corylown suggests.  It's not clear to me how far back it's useful to keep it (or if there's any problem with keeping it indefinitely, if there's some sort of chronological paging that could keep the display from getting overwhelming).

It would be helpful to have some sort of link to documentation or controls in or near the "needs attention" panel, since an uploader may be thinking "OK, I see some jobs need attention-- what can or should I do about that?"

It's not clear to me that a stalled job and a job that failed but will be retried should be recorded or displayed the same way, as Cory seems to be suggesting.  They seem to represent different exceptional cases and different time frames, and might also call for different responses.  I realize they both represent different flavors of "having problems at present, but might succeed in the future" though, and we may get a better sense with experience and user feedback on whether it's clearer to show them the same way or differently in the interface.

Thanks for the detailed design and comments!  I look forward to further development and discussion of this feature.

**Comment by corylown** [comment]
> It's not clear to me that a stalled job and a job that failed but will be retried should be recorded or displayed the same way, as Cory seems to be suggesting. 

No, I agree they should be treated differently in the UI. A stalled job is one that failed at least once but is queued up to retry (in the `Sidekiq::RetrySet`) and could succeed in later attempts. A failed job has been retried and sent to the dead jobs queue after the configured number of tries have failed (in the `Sidekiq::DeadSet`).

I agree it would be helpful to provide a way in context to get help with failed or stalled jobs. For now I think that would be the wiki: https://github.com/pod4lib/aggregator/wiki#getting-help
