### ISSUE TITLE
Investigate current production environment compute and disk resources & determine what we think we need.

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#414]

**Comment by JohnMarkOckerbloom** [comment]
As a start for this issue (which will need to carry over into iteration 3, by the look of it), it would be helpful to establish an initial estimate of what we expect adequate compute and disk resources to be for the production environment.  We probably can estimate roughly how much storage is needed for the raw files, based on what's been uploaded to date from the various institutions and how long we plan to keep files and streams around, and then add estimates on how much more storage is likely to be required for normalized files, databases, caches, application code and libraries, and contingency space.  Similarly, logs on past activity may give us an idea on the computation resources needed to process uploads in a reasonably timely manner.  We'll also need to plan on computational and storage resources needed for the OAI service.

Is there someone on the team who can do some initial measurements and estimates (subject to revision later as needed)?  It's probably be useful to have it be someone who can see more of the Stanford server infrastructure than I can from here.  Then we can put in requests for allocation of any resources we don't already have.  (Given how long it's taking to get a staging server set up, I'm thinking it would be good to figure out what we need to ask for sooner than later, to allow enough time for a possibly slow  response.)

**Comment by corylown** [comment]
To start estimate records we think we'll have in the near term (100,000,000 records) and check whether we have enough disk space.

**Comment by thatbudakguy** [comment]
# disk space
## usage
here's a look at disk usage.
* we're using **70%** of our ~350G volume dedicated to the postgres database.
* we're using **73%** of the ~600G volume dedicated to the app itself.
* there's a 500G nfs volume mounted on `/data` that is currently empty.
```
Filesystem                  Type      Size  Used Avail Use% Mounted on
/dev/mapper/rootvg-slash    ext3      9.8G  5.7G  3.6G  62% /
/dev/sda1                   ext3      482M  136M  321M  30% /boot
/dev/mapper/rootvg-afscache ext3      976M  1.3M  924M   1% /usr/vice/cache
/dev/mapper/rootvg-tmp      ext3      197G  6.2G  183G   4% /tmp
/dev/mapper/rootvg-var      ext3       20G  2.5G   17G  14% /var
/dev/mapper/rootvg-app      ext3      596G  414G  158G  73% /opt/app
/dev/mapper/rootvg-pgsql    ext3      345G  230G  101G  70% /var/lib/pgsql
sf6-prod:/pod_data_prod     nfs       500G  1.3M  500G   1% /data
```
we're using the ext3 filesystem, although ext4 has been the default in a lot of linux distributions for awhile. this might be worth keeping in mind, since:
* ext3 can't handle dates after 2038
* ext3 can't handle disk sizes larger than 16TB
* ext3 can result in heavy fragmentation when there are a lot of concurrent writes (not sure if our sidekiq jobs do this)
* ext3 can't have more than 32,000 subdirectories in a directory (not sure if this will matter for storage)

ext4 solves all these problems and was designed to be an in-place upgrade for ext4 (see this [article with some more info](https://opensource.com/article/18/4/ext4-filesystem)). i'm not an expert, but it might be worth checking with ops to see how they feel about ext3 in light of our potential use patterns in the future.

as expected, the app volume is virtually all dedicated to storage for uploaded files.
```
28K	/opt/app/pod/aggregator/shared/config
15M	/opt/app/pod/aggregator/shared/repo_configs
1.7G	/opt/app/pod/aggregator/shared/bundle
8.0K	/opt/app/pod/aggregator/shared/vendor
711M	/opt/app/pod/aggregator/shared/tmp
38M	/opt/app/pod/aggregator/shared/public
409G	/opt/app/pod/aggregator/shared/storage
```
* we currently have **32,213 uploads**.
* there are **27,885 attachments** to these uploads taking space on disk (i.e. files and not URLs).
* these range from a handful of bytes to 4.5G. the median size is about **14Kb**, but the average is about **16Mb**.
* over nearly a year of data, the median number of files uploaded each day is **69**.
## prediction
it's tough to guess at the usage patterns because the files vary in size so drastically, but if we go with mean upload size, we can expect about **1.1G** of uploads per day. at this rate, we would fill up the app volume in about **140 days**.

this of course doesn't take into account the `CleanupAndRemoveDataJob`, which runs every 3 months, and will remove any files tied to non-default streams that haven't been updated since the last time it ran. it's unclear how many of these files would be affected by that job.
