### ISSUE TITLE
Right-align numeric table columns

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#426]
The various tables currently in POD tend to contain a lot of numeric data. Numeric table data is easier to scan, comprehend, and compare (e.g., larger values are more apparent at a glance) when they are right-aligned in the table column.

We'll probably want to do other visual refinement related to POD tables, but a good start would be to right-align the numeric columns listed in the tables below. Note that for each column where the values are right-aligned, the table header for that column should also be right-aligned.

(It would be nice to right-align the Size column in relevant tables as well, since this is basically a numeric field. But we're including units in the value of that column, and several different units at that ("GB" versus "Bytes"), which complicates things. So maybe we can leave this column as-is for now and come back to it when other table improvements have been completed.)

Headings below are table names; checkboxes are the columns that need realignment.

#### Organizations
- [x] Files
- [x] Unique records
- [x] Total records

#### Organization
- [x] Records

#### Normalized data
- [x] Records

#### Activity/Uploads
- [x] File count
- [x] Records

**Comment by marlo-longley** [comment]
@ggeisler I'm starting to look into this, thanks for compiling it.

I noticed that in the MVP codebase, it looks like the intention was to have every column including headers and non-numeric columns have the text align to the right. Maybe this wasn't an intention, just a random thing. But you can see the `text-right` class applied to everything. However, that class was removed in BS5, so that's why everything reverted back to left alignment.
![Screen Shot 2022-03-17 at 15 28 45](https://user-images.githubusercontent.com/1328900/158904840-d1bb35e4-b526-43e1-a86e-9cae59f3341b.png)

I'm wondering if I should realign everything to the right again, rather than pick and chose only the numeric columns like you indicated here.

**Comment by ggeisler** [comment]
@marlo-longley Sure, if you want to just change all the `text-right` classes to `text-end` we can see how that looks and go from there. You're right, that might be a simpler way to go given the current code.

**Comment by marlo-longley** [comment]
@ggeisler awesome, thanks for your input! Seems simple for now.

**Comment by marlo-longley** [comment]
Update: deciding to wait on this until more clarity on which tables and views will make it into the next design of the app.

**Comment by cbaksik** [comment]
Having commas in the numbers is very helpful as well. I see them now but don't think they were always there. Wanted to affirm that they are desired.

**Comment by ggeisler** [comment]
👍 I'll keep an eye on that as we finalize the display details later in the workcycle.

**Comment by corylown** [comment]
Closed by #656

**Comment by corylown** [comment]
Oops #656 is not merged yet...
