### ISSUE TITLE
Provide contact information in the POD app for requesting help with data submission or consumption.

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#429]
It may be sufficient to link here: https://github.com/pod4lib/aggregator/wiki#getting-help

**Comment by ggeisler** [comment]
Since we already have a persistent place in the app for linking to documentation and project resources (the footer), I'd suggest we add a link to the wiki page there. In the mockup below, I've added a link as the first item under "Other Resources". (Note that I've also updated the labels of all the other links in the "Documentation" and "Other Resources" section to make them a bit less abrupt or to be a bit more descriptive.)

<img width="1178" alt="update-footer-links" src="https://user-images.githubusercontent.com/101482/157140540-e2a03a28-90c6-49dc-92b1-1bab2d79407e.png">

---

Also, I have plans to update the content on the application homepage to be more helpful to users. I haven't started on that yet but I think it might be possible to include a reference to the wiki page there as well, which would be more prominent and potentially more noticeable by new users. But that would be a less persistent (i.e., visible only on the homepage) reference, so I'd consider that a secondary reference and rely on the footer link as the primary point of reference for this.

**Comment by corylown** [comment]
Also need to change the date in the footer.

**Comment by ggeisler** [comment]
@JohnMarkOckerbloom That definitely seems worth considering. I created #464 to capture that idea, because I think the PR to close this issue is valuable on its own and I don't want to delay merging that, or losing track of your idea if we do merge it before we have a chance to design how it would look.
