### ISSUE TITLE
Update layout of the Activity uploads table

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#477]
Refers to this view in the application: https://pod.stanford.edu/dashboard/uploads
<img width="1336" alt="Screen Shot 2022-03-16 at 5 44 21 PM" src="https://user-images.githubusercontent.com/458247/158696283-6e8ed2dd-1dc4-46cf-b070-ae85c0f362ee.png">

Particular areas that need attention:

- Each entry comprises two separate rows with some information repeated and other information that is different. The design should be cleaned up to remove the repetition and clarify the information displayed.
- The first row contains a link to a view in the app for just that upload. The second row contains a link directly to download the uploaded file. The distinction between these links should be clearer.

**Comment by ggeisler** [comment]
Just noting that when we finalize the icons to be used in #425, we should update the icons used in the uploads table as well, both to be consistent in our use of icons and to eliminate the current icons on this page, which can be interpreted as action buttons, rather than status icons, at least in some cases.

**Comment by ggeisler** [comment]
Below is a recommended update to the current uploads table on the Activity page.

Not sure if it is a final decision, but in https://github.com/pod4lib/aggregator/issues/516 we seem to be saying that we will not surface "uploads" directly in the UI; users don't need to know anything related to "uploads".

Given that, by not having to include the name of the "upload" in the table, the content of the uploads table becomes very similar to the files table on the provider page, so using the files tables as basis for uploads table might make sense (at least conceptually, although the new table structure changes quite a bit so copying code from it to replace the current uploads table might make sense, too):

<img width="1145" alt="Screen Shot 2022-04-18 at 3 40 52 PM" src="https://user-images.githubusercontent.com/101482/163891164-727ae787-1235-40be-949f-0e2679fc898b.png">

---

- [ ] **A:** Add the file status legend above the table, just as we do with the provider files table.
- [ ] Omit display of the "upload" name, which is currently shown as the first line of the "Name" column for each record. It's the display of both the name of the "upload" and the name of the upload file that resulted in the two-line row structure of the current table, which creates some problems. So omitting the display of the "upload" name enables us to dispense with the two-line row approach and simplify the display of the table rows.
- [ ] **B:** Move the file status column to be the first column (it is currently the last column) and add `Status` as the column name.
- [ ] **C:** Rename the "Name" column to `File` and just display the name of the file uploaded as discussed above.
- [ ] **D:** Rename the "Updated" column header to `Date created`. This is to be consistent with the files table, though I don't feel strongly that they need to be the same. In the mockup I've also adopted the same date format as in the files table, instead of the current "27 minutes ago" style. Again, I don't feel strongly about this and still think we need to take a [holistic view of our date/time display formats](#509), but I think the "... ago" format works less well when you get a ways back into history and only get "about 2 months ago", which doesn't seem very helpful if you are trying to track down a problem with a file or figuring out exactly when something happened. 
- [ ] **E:**  Move the column currently called "Organization" to the new location and re-label it `Provider`. Also, omit the organization logo.
- [ ] **F:** The three remaining columns exist in the current uploads table. `Size` is the same as the current table's "File size" column. The header and values for this column should be right-aligned.
- [ ] **F:**  `Content type` isn't labelled in the current uploads table because of the two-line row thing. So that sort of becomes a new column with the values currently shown on the second line of the "Updated" column. (I do wonder if we could eliminate the "content type" values from this table, though, since between the file status and the file name it is usually obvious what kind of file it is and the strings just add visual noise? But we can consider that later.)
- [ ] **F:** Remove the current "File count" column, since we're showing one file per row as the basis of the revised table.
- [ ] **F:** "Records" is the same as the current "Records" column. The header and values for this column should be right-aligned.

**Comment by corylown** [comment]
Since this activity page is limited to POD Admins only I'm wondering whether we ought to leave the information about uploads as it is. Maybe it's useful for diagnostic purposes?

**Comment by ggeisler** [comment]
I guess that is the question, is uploads information useful to anyone? If not, it is making the uploads table unnecessarily complicated and arguably less useful.
