### ISSUE TITLE
Investigate why file names sometimes display as timestamps

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#479]
This occurs in various places in the application, including the dashboard/upload page: https://pod.stanford.edu/dashboard/uploads
<img width="489" alt="Screen Shot 2022-03-16 at 5 50 54 PM" src="https://user-images.githubusercontent.com/458247/158697280-882807f5-fd4e-4ce5-99ef-c58dc05bf33b.png">

In Harvard's entry above the first row is a link to the upload page and is displayed as a timestamp. The link in the second row is a link to download the file and is a filename.

In Dukes's entry above the first row is a link to the upload page and is displayed as a filename. The link in the second row is a link to download the file and is also a filename.

Why are these displayed differently? Is one a fallback? Is there a clearer way to label these links?

**Comment by thatbudakguy** [comment]
i think this is a combination of two things.
1. the fallback behavior if no name is specified for an upload is to use its timestamp as the name:
https://github.com/pod4lib/aggregator/blob/5a54de690124d57016ba846006bc40372bc29726/app/models/upload.rb#L29-L31
here's two uploads I made, one where I specified the name "testing name" and one where I didn't specify any name. each contains one file; the second line is a link to that file.
<img width="879" alt="Screen Shot 2022-03-16 at 15 40 40" src="https://user-images.githubusercontent.com/4924494/158703327-5333cdf4-6482-4ec5-a80f-3aa527a19719.png">

2. duke is explicitly using the filename of the (single) uploaded file as the name of the upload itself, so the upload name matches the filename exactly.

**Comment by thatbudakguy** [comment]
i wonder if it would help to just always name uploads according to a unique identifier, like a UUID. even just using the database ID might not be so bad, since uploads only need to be unique per organization.

relatedly, we might want to consider not listing all the files underneath each upload on pages that primarily list uploads (like this one). it makes for a confusing UI in what seems to be the most common case (1 file per upload) and could also lead to a weird-looking UI if there were a ton of files in a single upload. since you can get the files by just visiting the upload's page, idk if we need to try to show the in the same table as the upload itself.

**Comment by corylown** [comment]
Waiting on design decisions to decide what to do.
