### ISSUE TITLE
Does access to the OAI-PMH feed need to be restricted somehow?

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#481]

**Comment by JohnMarkOckerbloom** [comment]
Answer from Friday's POD workcycle meeting: Yes, it needs to be restricted (because the data's not been deemed open enough to allow unrestricted harvesting).

It seemed cleanest to restrict if via http[s] Basic authentication, using the same access tokens already created in the system.  However, since Index Data's OAI harvester doesn't currently support Basic authentication, we might need to consider backup methods such as IP address permissions.

**Comment by anarchivist** [comment]
@JohnMarkOckerbloom To clarify, our authentication is currently based on [bearer tokens](https://www.rfc-editor.org/rfc/rfc6750).

**Comment by JohnMarkOckerbloom** [comment]
@anarchivist Ah, thanks for the clarification!  Hopefully Index Data will find a way to have that supported in their OAI client.

**Comment by JohnMarkOckerbloom** [comment]
Mark raised the issue of Index Data using bearer tokens at today's workcycle planning meeting.  I don't recall us getting a definite response on whether or when they'd be able to use those in their client.

**Comment by JohnMarkOckerbloom** [comment]
Sebastian at Index Data says their current OAI-PMH library is not able to use bearer tokens.  We'll probably need to implement IP-based authentication for them, at minimum, for this workcycle.  (Though it would be nice to use bearer tokens to serve other consumers.)

**Comment by corylown** [comment]
Closing this. Question is answered.
