### ISSUE TITLE
Add an attribute to Organization to indicate if an org is consuming data only.

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#482]
I'm thinking of IndexData specifically, but generally, we may need a way for an organization that is not contributing data, but is consuming data to manage tokens, users, and contact info.

**Comment by corylown** [comment]
Feedback from 3/18/22 work cycle management meeting:

> Maybe - may help address use cases around Goldrush access, and potential access of researchers. 

In general, this may be a nice to have, but not necessary to address this work cycle. We can likely get away with using the existing contributor type organization for generating tokens and managing users for IndexData.

**Comment by JohnMarkOckerbloom** [comment]
Also mentioned in that meeting: A toggle-able binary flag (rather than a separate type) might be sufficient to designate organizations that only consume and don't provide data, if that's a useful thing for aspects of the interface to recognize.

**Comment by ggeisler** [comment]
Given the planned redesign of the application, I'll just resurface this issue and suggest adding an attribute on Organization that distinguishes between a `provider` and a `consumer` might be more useful to add during this sprint than we previously thought. Examples of when knowing the org type would likely be useful when displaying pages:

- Homepage: the [customized organization section](#519) in particular, which will have different contents for each type
- Providers page - the table with the list of providers is really a list of organizations of the **provider** type, so we will need to differentiate between them  and consumers when displaying this table
- Provider page - since the consumer org has no streams, files, processing status, etc. we don't have an equivalent of the main provider page for a consumer org (we do have a similar "Organization details" page to manage the org users, contact address, etc. for the consumer org, but even there it is a bit different because consumers don't have Access tokens, Provider details, etc.)

But again, I'm just bringing this up for reconsideration given the application redesign, not suggesting technical solutions or priorities.

**Comment by corylown** [comment]
Add a `consumer_only` attribute on `Organization` for organizations that will not be contributing data.

**Comment by thatbudakguy** [comment]
in my head, it makes more sense to name the attribute something like `Organization.has_streams?` or `Organization.provider?`, since the functionality for provider orgs is a superset of the functionality for consumer orgs. Put another way, everyone is a consumer, but only some people are providers. feels like we might get a lot of `if !Organization.consumer_only` otherwise

**Comment by corylown** [comment]
@thatbudakguy I think that the default behavior is that an organization is a contributor and consumer and so a `consumer_only?` is a special type. I think it's preferable if the default behavior is in effect if the flag value is `false` (logic being that the non-default case should be a deliberate opt-in). We can always add a `provider?` method on the model for convenience.
