### ISSUE TITLE
Date format for files in streams

### ISSUE THREAD

**Issue by bobpersing** [pod4lib/aggregator#509]
The create date for a file in a stream currently displays in the UI as "day month time".  Since some of the current streams have existed for over a year now, it would be useful to display the year as part of the create date.

(Screenshot attached.)
![screenshot-pod stanford edu-2022 03 25-10_22_57](https://user-images.githubusercontent.com/74777933/160139275-0dbc67ea-c019-443e-8b22-7c9afd692ee3.png)

**Comment by ggeisler** [comment]
This relates to a larger issue with dates I was about to ticket. We currently display date/time values in several different formats:

<img width="1143" alt="Screen Shot 2022-03-25 at 9 32 28 AM" src="https://user-images.githubusercontent.com/101482/160162777-9b6b18b0-9a0e-4f4b-a721-d061993652c3.png">

---

<img width="250" alt="Screen Shot 2022-03-25 at 9 36 14 AM" src="https://user-images.githubusercontent.com/101482/160163147-fc7b8d29-990d-48a9-b3d2-8f9e39e09460.png">

---

There might end up being places we intentionally want to use a different format (maybe not, though), but in general I think we need to decide on a single date/time format we use consistently throughout the application. Considerations include:

- Making the format more user-friendly (e.g., not the format used in the processing status output)
- Decide how much precision we need in the time portion
- Deciding if we can either a) drop the timezone designation, b) use a consistent timezone, or c) detect the user's timezone and use that for the session

Since all POD participating institutions (to my understanding) are US-based, it seems like we should be able to standardize on single timezone if we want to display it, either based on the user's connection or just picking EDT or PDT (or whatever).

**Comment by cbaksik** [comment]
1 - Please drop seconds
2 - In some places the number has a Z at the end. Please drop
3 - LOVE the idea of making it responsive to user's time zone
4 - I prefer the 3-char month usage for if/when international partners join. That will help disambiguate from the Euro usage of day/month vs. month/day
5 - Agree that year would be helpful

**Comment by ktamaral** [comment]
@bobpersing @ggeisler @cbaksik I think the easiest way to fix this consistently throughout the application will be to use one of the built-in date formats in Rails. 

The 'long' format appears to meet the requirements, e.g.:
April 13, 2022 18:10

Another option would be to add a configuration value for custom date string formats which would be more work but allow more flexibility.

**Comment by ktamaral** [comment]
@bobpersing @ggeisler @cbaksik I've installed a library that converts the server's UTC time into the user's local timezone automatically. Also it has formatting options for display. I'll work on making this consistent throughout the application and open a PR.

`2022-04-26 14:41:49 UTC => April 26, 2022 10:41am`

**Comment by corylown** [comment]
I'm concerned that changing the timezone to display based on the user's location will make it difficult to debug problems, such as if a user reports that they see a problem with a file uploaded at a specific time, but I see a different time associated with the file when I view the app. At the very least, we should indicate the timezone to make it easier to understand what is being displayed.

**Comment by ktamaral** [comment]
@corylown I was able to add the client-side local time zone to the display using the date formatting options in the local_time module.

`2022-04-26 14:41:49 UTC => April 26, 2022 10:41am EDT`

**Comment by ggeisler** [comment]
@ktamaral I like this solution. The final feedback maybe should come from real POD users who would reference dates on a regular basis, but this seems worth implementing consistently throughout the application. Worst case, if we get feedback that this format is difficult for users to scan for their tasks or whatever (not really expecting to hear this), we could try another format then. But at least we'll have a consistent solution in place that should be relatively easy to change if necessary.
