### ISSUE TITLE
Adjust Manage/View organization page when org is consumer-only

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#535]
Related to #534.

Although most POD organizations are providers, we also expect to have at least one consumer-only organization. Some of the details described in #534 don't apply to consumer-only orgs, since they don't have access tokens or MARC details, but others do. 

The details below assume #534 is completed first, so these are the differences from #534 when the organization is consumer-only:

<img width="1198" alt="Screen Shot 2022-04-04 at 12 26 27 PM" src="https://user-images.githubusercontent.com/101482/161617517-f218c69c-e34f-4405-a27f-ef0d53445e91.png">

---

- [x] **A:** Since a consumer-only org doesn't have streams, we should omit the "Default stream" link we show to provider organizations.
- [x] **B:** Since a consumer-only org doesn't have access tokens or MARC details, we should omit the "Access tokens" and "Provider details" tabs we show to provider organizations.

The form on the Organization details page might need to be slightly different as well, because consumer-only orgs don't have a MARC organization code but I'll address that in a separate ticket about that particular page.

**Comment by thatbudakguy** [comment]
@ggeisler i'm getting confused about what the consumer org page should display (although maybe we don't have the answer to that yet).

- for providers, their homepage (what you get if you go to `/organizations/my-org`) displays their default stream and other relevant data. obviously this doesn't work for a consumer org.
- for providers, you get a link up in the top right to go to the org users page `/organizations/my-org-users`, which looks different depending on whether you are an owner or not. from here, you can get to any of the other "manage/view organization" pages, which we have styled to appear as tabs.

what should display when you go to the homepage for a consumer org? i.e. `/organizations/my-org`? right now, there's not really anything valid we could display, because it's all geared toward streams. i can't tell if the designs are implying that the content from the manage/view organization pages should be shown _on the org homepage_ for a consumer, but i don't think they are. should we just leave it blank?

hope this makes sense; not directly related to this issue but i figured i should raise it regardless.

**Comment by thatbudakguy** [comment]
other random thought...there are currently 3 ways to get to a consumer org's pages:
- click "providers" in the nav, which gives you a list of all organizations, not just providers (probably should fix this)
- log in as a member of a consumer org and visit the homepage, which gives you a link to your org
- directly paste/type in a link to a consumer org's page

and similarly, there's only 2 ways to create a consumer org:
- click "providers" in the nav and then click "create organization" and uncheck the "provider" box
- do it manually in the rails console

maybe we don't even care about allowing people to create consumer orgs in the UI, which I think would be fair? it just seems a little odd that these things have to go through a nav item called "providers" currently.

**Comment by ggeisler** [comment]
@thatbudakguy 

- I don't think we should show a consumer org on the Providers page. If I didn't explicitly say that anywhere that's my oversight but the idea with renaming to "Providers" is to just focus on providers on that page.
- Consumer orgs don't have the same "homepage" (org show page) as providers, as you note, because the content there isn't relevant to them. The intention is for the consumer "homepage" to be their Manage/View organization page. 
- When we remove the consumer org from the providers page list, there shouldn't be a way for a non-POD-admin user to get to a consumer page. I'm assuming this is fine and desired.
- When we remove the consumer org from the providers page list, a POD admin should have access to their Manage/View organization page (since they have access to any page). But, there is no link in the application UI to get there (i.e., a "Consumers" link that is similar to the "Providers" link/page). I kind of already knew that, but it seemed like enough of an edge-case that it would be easier to remedy after we got the rest of the application re-organization done.
- I'd agree with "we don't care right now" that there isn't a way to create a consumer org through the UI. Again, it seems edge-case enough to just deal with it via the console for now (at least until we hear that there will be more than a couple of consumer orgs).

**Comment by thatbudakguy** [comment]
> The intention is for the consumer "homepage" to be their Manage/View organization page.

ah ok, this is what was confusing me. i think the issue is that currently, the "manage/view organization page" is actually four different pages, which we render as tabs:

- `/organizations/org/users`, "Users" (the one you see first)
- `/organizations/org/allowlisted_jwts`, "Access tokens"
- `/organizations/org/organization_details`, "Organization details"
- `/organizations/org/provider_details`, "Provider details"

for consumers, it's just a subset, as noted in this issue:

- `/organizations/org/users`, "Users" (the one you see first)
- `/organizations/org/organization_details`, "Organization details"

the problem is that if the org's homepage (`/organizations/org`) _is_ their Manage/View organization page, then...where do `/organizations/org/users` and `/organizations/org/organization_details` go? or, does `/organizations/org` just redirect to `/organizations/org/users` (the default/first tab)? or do we duplicate the "manage users" table in both places?

**Comment by ggeisler** [comment]
When I was doing the page redesign, I knew the consumer-only org was going to be the trickiest part, so sorry for the complications... This feels like the weakest part of the redesign to me, but we only have one consumer org so it also doesn't feel like it deserves a lot of redesign around it specifically.

> or, does /organizations/org just redirect to /organizations/org/users (the default/first tab)?

This sounds like the best solution to me. One reason I like this is it should make it relatively easy for us to revert back to `/organizations/org` as the consumer homepage, if (I have no idea whether this will happen but who knows) we ever decide that consumers do have something useful to share with other POD users on their "homepage". Plus a simple redirect just seems like the most straightforward, although I am not qualified to give technical advice....
