### ISSUE TITLE
Display the organization contact value as a link

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#545]
EDIT: we settled on only using a single email address for the organization contact field. I've updated some of the original ticket description to match that decision.

In #544 we're moving the organization email contact to be a single-valued attribute of organization. ~~We've also discussed allowing the value of this field to be either an email address or a URL (e.g., maybe the organization wants people to go to a page they've set up locally to provide more info about their POD stuff).~~

~~I'm not sure if there are any technical hurdles to storing either an email address or a URL in the same field, or in then displaying whichever is stored as a different type of link, but I'm assuming not and we can discuss alternatives if the idea below doesn't make sense.~~

- [x] Display the value of the organization contact field as a link in the organization banner, with the label `POD contact for this organization`:

<img width="1197" alt="Screen Shot 2022-04-04 at 4 11 51 PM" src="https://user-images.githubusercontent.com/101482/161647396-01d19f47-e1b3-4606-b696-c666f519f2e0.png">

---

- [x] ~~If the value is an email address,~~ use the `mailto:` form of the link, ~~otherwise a standard link~~
- [x] If the organization has not entered a value for their contact, don't display the label:

<img width="1197" alt="Screen Shot 2022-04-04 at 4 12 36 PM" src="https://user-images.githubusercontent.com/101482/161647505-28bdc8d1-b8f8-4dc6-9815-0b0bb3b40867.png">

**Comment by ktamaral** [comment]
The contact field is a multi-valued email field right now. The proposal is to make it single-valued. We will have to deal with the edge case of multiple values until that gets settled. Also we are only expecting email for that field and not a url to a form so that simplifies things a bit.

**Comment by JohnMarkOckerbloom** [comment]
I have not to date heard from anyone who needs a contact URL.  I think we can make this simply a single email address for now.

**Comment by ggeisler** [comment]
Sounds good @JohnMarkOckerbloom.

We still have the single-valued versus multi-valued aspect of this to deal with. Although we only have one organization using more than one value, and I feel it would simplify things without being unreasonable to make this field single-valued and ask the one org to settle on a single email address for their contact, I suppose another option would be to maintain this field as multi-valued and use all values in a single mailto link. Here's an example of how that might be done (although you might be able to add all values to the "to" part, instead of using "cc", maybe?):

https://css-tricks.com/snippets/html/mailto-links/#aa-adding-cc-and-bcc

**Comment by JohnMarkOckerbloom** [comment]
As mentioned in today's update, we're going with a single contact email address per organization.  In any case, though, the URIs in the mailto: links should be appropriately escaped, as per RFC 6068 ( https://datatracker.ietf.org/doc/html/rfc6068 ).  I'm not sure all the examples on the css-tricks.com site are, though some browsers might tolerate them.

**Comment by ktamaral** [comment]
Documenting this conversation from slack:

[Katie Amaral]
Since we are now going to have only one contact email per organization, do we need to add a new field to the organizations model? Or are we going to still use the contact_email model? And if we are using the contact_email how do we make sure to pick the correct one when we query the contact email addresses for a given organization?

[Cory Lown]
That’s a good question. I know we already have one organization with two contact emails so we will need to migrate or remediate some data. (I think only two orgs have submitted a contact email so it’s a small task.) I suppose we could either create a new attribute on organization for this single-valued field or change the behavior of the current model so that an organization can only save one despite the underlying one to many relationship.

[Cory Lown]
Might be simplest to just create a new attribute, remove the existing model and manually migrate the data we want

**Comment by ktamaral** [comment]
I looked more into the possibility of creating a new attribute on the organization model and removing the contact_emails model. The contact_emails model has quite a bit of functionality built in for the email confirmation token, etc. So I think perhaps it may be easier to keep the current contact_emails model and updating it to allow adding one contact only.

Also I'm looking into whether the built-in mail_to method in Rails does the escaping for RFC 6068 ( https://datatracker.ietf.org/doc/html/rfc6068 ) or if an additional method needs to be applied.

**Comment by corylown** [comment]
@ktamaral I'd say go ahead and implement what seems most straightforward to you.

**Comment by thatbudakguy** [comment]
I ended up doing this work as part of https://github.com/pod4lib/aggregator/pull/647 since I was working on the header already anyway. right now it just assumes that `Organization.contact_emails` will still exist and picks the first; I think we can update that logic when we do #544, which should be trivial to do. I think that means this issue can be closed once #647 is merged; lmk if that doesn't seem right.
