### ISSUE TITLE
Provider page > Processing status

### ISSUE THREAD

**Issue by cbaksik** [pod4lib/aggregator#560]
In the Processing status section #531 move "Needs attention" above "Currently active" and have "Needs attention" open by default.

**Comment by ggeisler** [comment]
👍 This makes sense to me. 

Probably obvious, but "Needs attention" tab should only be open by default if it includes one or more jobs. Otherwise, "Currently active" should be open by default, if it includes one or more jobs. Otherwise, "Completed" should be open by default, if it includes one or more jobs. If no tab includes jobs, no tab should be open.

**Comment by ggeisler** [comment]
A new, additional suggestion for the processing status section is in #576. It's completely fine to handle that separate from this, just want to point it out in case the developer working on this ticket wants to tackle that as well, since it involves the same section of code.

**Comment by ktamaral** [comment]
Pull request: https://github.com/pod4lib/aggregator/pull/582
