### ISSUE TITLE
Determine how to manage and request data by sets (organizations) to support harvesting by set via OAI-PMH

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#569]

**Comment by JohnMarkOckerbloom** [comment]
To expand on the basic issue title, and spell out some of the implications:
- We're aiming to have one set per provider organization (not per stream).  OAI clients can request harvesting in full or with time-bounds from any of those sets. They can also make a request that doesn't specify a set.  (A set-less request can be fulfilled by iterating over all the provider sets and returning all relevant records from each of them.)
- The records in each provider's set are distinct from the records in the other sets.  (No record is in more than one set.)  One implication of this is that records in different sets need to have different IDs.  (One easy way of handling this is to make OAI record IDs consist of a unique prefix for each provider, followed by a separator, followed by the 001 ID of the record as uploaded.) 
- Names of all the provider sets (which might be the same as those unique prefixes) should be returned in response to the ListSets OAI verb.  The ListSets response can also include more information about sets in setDescription elements, such as the full name of the provider.  That might also be somewhere to put information about when the most recent change in the default stream for the provider was made, which could suggest when the last full dump was finalized.  (Some clients might use this information to decide they want to do a full harvest of the set, rather than an incremental harvest that starts before that time.  But I haven't heard from anyone yet that this is needed; so consider such time information a convenience that might be nice but isn't required.)

**Comment by corylown** [comment]
Replaced by #711
