### ISSUE TITLE
What are our performance goals for OAI-PMH?

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#571]
- 1 million records per hour could be ideal
- But what’s the slowest acceptable

**Comment by JohnMarkOckerbloom** [comment]
I recall Index Data saying at a previous workcycle meeting how fast they processed records; I'll see if I can find that figure in the notes for previous meetings, or ask them about it on Friday if I can't.  (I think we don't need deliver faster than they can process, and my recollection of the rate was that it was slower than the ~300 records/second that HathiTrust's OAI feed now delivers.)

In any case, the implementation should be such that the rate of record delivery should not substantially decrease over the course of larger sets, and the latency of individual responses should not be so long as to result in common timeouts.  (The older OAI feed used for HathiTrust, once you got far enough into the iterative requests for a full dump, could have latencies of over 6 minutes long, and effective throughput of 1 record/second or worse, due to the inefficient way it was handling resumptions over large result sets.)

**Comment by JohnMarkOckerbloom** [comment]
I asked Sebastian at Index Data about this today (specifically, how many records do they anticipate being able to process per second or other unit time; and what rate of transfer would they consider a minimum to be usable for their purposes).  He said he'd get back to us about that.  I might want to ping him on this next week if I haven't heard from him, and/or bring the issue up on the oai-pmh-testing channel on Slack.  (I'll plan on doing the latter Monday or another time early next week.)

**Comment by JohnMarkOckerbloom** [comment]
From Sebastian's response to @corylown , it sounds like Index Data wouldn't be processing more than 500,000 records/hour (or about 140 records/second), and that they can also accommodate slower but reasonable speeds.  ("[T]here's really no issue if we're not totally aligned on performance" he says.)

**Comment by corylown** [comment]
Closing this since the question is answered. We will want to test the performance to make sure it is acceptable once the OAI implementation is complete.
