### ISSUE TITLE
Generate an inter-stream delta for a stream

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#601]
Given work on #619 it likely makes sense to start by generating interstream delta files (marc21, marcxml & oai) that contain records that have changed since the previous stream.

~~Blocked by #599~~

This is likely to be a slow process and may need to be calculated as a background job and stored in a file ~~or the database for future reference:~~

~~GenerateInterStreamDeltaJob: Given a current or former default stream generate a list of MARC record 001 IDs for records that have NOT changed between the given stream and the prior default stream (or streams, depending on the method employed). Store this list in a file or db table associated with the given stream (or associated with the stream's history if we allow streams to become a default more than once).~~

**Comment by JohnMarkOckerbloom** [comment]
This may be a convenient data structure to generate for efficient implementation of incremental harvesting.  It's not strictly necessary, however, and can be dropped if it doesn't make implementation easier or more efficient.  (The developers can tell whether it does more easily than I can.)  What an incremental OAI harvest needs to return are the records that *have* changed (including information on those that have been deleted, which is why inter-stream deletes are important to calculate), rather than the records that have not.

**Comment by corylown** [comment]
Closed via #714
