### ISSUE TITLE
Harvard: Understanding the Normalized data file list

### ISSUE THREAD

**Issue by cbaksik** [pod4lib/aggregator#613]
Using Stanford as an example, there are 2 full sets available (one xml, one binary), dated April 14. There are also 2 deletas (xml, binary), and one delete files. 

My understanding is that the full set represents the current set of data in POD for Standard, i.e. whatever data was sent to first populate the stream, integrated/updated with all updates/add/deletes incremental files since then. If this is correct, then why is there a delta and a delete file as well? 

![image](https://user-images.githubusercontent.com/788203/163591347-ba9b8177-a8e7-42df-8cab-b00cc1c4f284.png)

**Comment by corylown** [comment]
The deltas and deletes are the changes since the full dump was generated. Full dumps are generated every 3 months and deltas are generated daily.

**Comment by cbaksik** [comment]
Could there be a hyperlink next to Normalized data with an "info" or ? that goes to this explanation? I don't believe this is explained in the wiki anywhere (i.e. fulls are generated every 3 months...). I remember this now from a POD meeting but couldn't find anything in writing. tyvm

**Comment by ggeisler** [comment]
@cbaksik @corylown I wonder whether it would be useful to introduce a new pattern for places in the application like this where there's a decent chance a user doesn't fully understand what is being presented. Rather than just a link to the wiki, providing some actual explanation on the page for reference, so the user doesn't have to interrupt their task by leaving the application to go to the wiki. See a possible approach below, using the updated version of the Normalized data page:

<img width="1037" alt="Screen Shot 2022-04-15 at 11 39 24 AM" src="https://user-images.githubusercontent.com/101482/163608786-13cd491f-8996-4ed1-bbf8-d6e1cbc2327a.png">

It's possible this is overkill, but I do have a sense that POD might regularly get visitors who are either new or infrequent, and quick in-place definitions or reminders might make sense?

If so, we could keep an eye out for other places where this pattern might be helpful and use it consistently.

**Comment by corylown** [comment]
@ggeisler I like your proposed pattern for providing this kind of information in context.

**Comment by cbaksik** [comment]
sound hugely helpful

**Comment by corylown** [comment]
Closed via #621
