### ISSUE TITLE
Org owner's topbar select menu includes duplicate link

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#637]
When logged in as an organization owner, I see an duplicate link to my organization in the topbar user menu:

<img width="543" alt="Screen Shot 2022-04-19 at 9 21 13 AM" src="https://user-images.githubusercontent.com/101482/164051821-22fb9ca3-0321-48c9-bddb-e298d0dd9c06.png">

**Comment by marlo-longley** [comment]
I just want to note that this issue is due to our roles structure. For example, if a person was added as a member of an org first, and then also added as an owner, they have two roles, and the logic is showing 2 links.

Not sure if we want to change this underlying logic, or simply suppress showing the link more than once.

**Comment by ggeisler** [comment]
Okay. It seems weird to me that a user can have two roles, rather than just having a single role that is replaced when changed. Not trying to weigh in on technical decisions, just noting that that seems like something worth fixing in the long-run, unless it doesn't make technical sense in this application for some reason.

**Comment by cbeer** [comment]
Rolify suggests adding an association like:

```
has_many :organizations, through: :roles, source: :resource, source_type:  :Organization
```
https://github.com/RolifyCommunity/rolify/wiki/Usage#finding-roles-through-associations

🤷‍♂️
