### ISSUE TITLE
Penn: delete files being treated as adds

### ISSUE THREAD

**Issue by bobpersing** [pod4lib/aggregator#696]
Penn is currently sending MARCXML records for deletes, with the leader 05 position coded "d".  Looking at the Penn provider page, though, the delete files have the same green icon as the other incrementals (the adds and updates), not the green icon with an X in it that denotes deletes.  (Screenshot below.)

We wonder if this is because our delete files are gzipped together with our other incrementals.  Is it necessary to send the deletes separately?  Should we not gzip the delete files?  (They're much smaller, so that would be possible.)

FYI, Brown sent some MARCXML files from Alma that seem to have processed correctly.  They don't appear to be gzipping any of their files. 

<img width="1182" alt="Screen Shot 2022-04-26 at 8 45 10 AM" src="https://user-images.githubusercontent.com/74777933/165303085-169cac69-dc2b-465d-b64f-53a1dc2d87e3.png">

**Comment by corylown** [comment]
Brown is sending their deletes incorrectly and the green X icon is a symptom of these MARC record style deletes being identified as text deletes because of the incorrect `.delete` file extension; see #652. MARC records sent to POD will be identified with a green icon (no X) because MARC adds, updates, and deletes can be mixed together in the same file. The Penn files are being identified and processed correctly. The only files that will be identified with a green X icon are text file deletes that are a list of 001 IDs to delete.

**Comment by bobpersing** [comment]
Thanks.

Should we change the legend for the green-icon-with-X to something like "deletes (text file)"?

**Comment by corylown** [comment]
Closing this. We've clarified the icon labels.
