### ISSUE TITLE
Uploads edit route does not exist

### ISSUE THREAD

**Issue by marlo-longley** [pod4lib/aggregator#774]
Reflected in the live app:

From the uploads page: [https://pod.stanford.edu/organizations/stanford/uploads/](https://pod.stanford.edu/organizations/stanford/uploads/) try clicking an Edit link and get the page does not exist error.
e.g. [https://pod.stanford.edu/organizations/stanford/uploads/18464/edit](https://pod.stanford.edu/organizations/stanford/uploads/18464/edit)

This has implications for #745 -- do we want to include the redesigned Edit button if such a route does not exist? Should we remove this button and simply link to the uploads#show page for that upload? Or do we need to fix the routing.

@ggeisler @corylown

**Comment by ggeisler** [comment]
@marlo-longley Good question. I noticed that the edit action didn't work as well when working on the mockup  (should've ticketed that), but assumed it was just a bug. But I guess the first question should be: does it make sense to edit an upload? Maybe it does (if you want to change the name of the upload, for some reason? or, can you add files to an upload?). If so, the mockup is correct and we just need to fix the link.

But if there is no reason for editing an upload, and the link is just currently there because this was just the default index page Rails generated, then we should omit the Edit buttons shown in the mockup.

**Comment by corylown** [comment]
I would be inclined to omit the Edit buttons for now. I can't think of a reason we'd need to provide the ability to edit an upload after it's submitted. If we learn otherwise we can add the Edit button and route needed to support it.

**Comment by marlo-longley** [comment]
@ggeisler @corylown Sounds good. Currently owners and POD Admins have `:crud` abilities on Upload, so technically they can edit/update an Upload. I will leave the ability alone and just remove the Edit button from the UI.

**Comment by marlo-longley** [comment]
Fastest issue close ever!
