### ISSUE TITLE
"New upload" buttons on upload index and show pages are ambiguous

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#781]
@ggeisler I noticed this while reviewing PRs for #770 & #775. The "New upload" buttons/links are ambiguous.

## Upload Index

On the index page the uploads shown can be associated with any number of different streams. It's unclear in this context which stream a new upload would be associated with. The current behavior is that the upload will be associated with the current default stream. I think we should indicate this somehow in the UI. The solution might be as simple as changing the text on the button to: "New upload to default stream" -- but maybe that's too long.
<img width="1032" alt="Screen Shot 2022-05-05 at 5 44 09 PM" src="https://user-images.githubusercontent.com/458247/167031139-1037468e-edfe-4689-be07-15e850fdcca4.png">

## Upload Show

On the show page it's especially confusing when you're viewing an upload from a stream that's not the default because you might be expecting to add an upload to the stream associated with the upload you're currently viewing. But that's not what happens. Just like on the index page it adds the upload to the current default stream. I think I'd suggest either removing the "New upload" button from the show page or clarify the button text here as well.
<img width="1039" alt="Screen Shot 2022-05-05 at 5 43 46 PM" src="https://user-images.githubusercontent.com/458247/167031501-62170dec-96ec-4611-8a22-2062d08d7681.png">

**Comment by ggeisler** [comment]
Yeah, I see what you mean. I'd suggest:

### Uploads index page
- Change the button label as @corylown suggests: `New upload to default stream`

### Uploads show page
This is a little more complicated but if we can do it it makes sense to me:

- If the upload on the show page is associated with the default stream, leave the button label as-is
- If the upload on the show page is associated with a **non-default stream**, do not display the New upload button at all

My reasoning for the difference here is:

- A user looking at an upload associated with a non-default stream seems unlikely to want to move directly from that task to making a new upload to the default stream (I'm guessing, but I can't really imagine that scenario to be common), so no point cluttering the UI with unnecessary (and potentially confusing) action.
- A user looking at an upload associated with the default stream, on the other hand, might be actively doing tasks related to uploads, so keeping the New upload button there seems useful. But making the label longer seems unnecessary since "New upload" will do what the user would very likely expect, since they are already looking at a default stream upload.

I can be overruled here and we can update to the longer label `New upload to default stream` on the show page as well, I'm just less comfortable with the longer label in this context because 1) we have less room in the button area, and 2) I  slightly worry that even with a more explicit label a user looking at a non-default steam upload might still expect the button to upload to that stream, so omitting the button in that context prevents that potential error.
