### ISSUE TITLE
Uploads tab of Activity page should display uploads summary for all orgs

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#818]
Relates to https://github.com/pod4lib/aggregator/issues/674 that was recently implemented.

Chicago is notably missing from the table on this page https://pod.stanford.edu/dashboard/uploads because their most recent upload is outside the 30 day window of the current logic. I think we want to show a summary for all orgs regardless of when their last upload was (in fact, it seems important and useful to show that an org has not uploaded in a while).

Change the logic for fetching upload summary info to include uploads for orgs beyond the current 30 day window.

There may be performance issues to address here as well if we expand the query to fetch data beyond 30 days ago.

**Comment by JohnMarkOckerbloom** [comment]
If there are performance issues for going too far back, is including an extra "last upload" entry in the database feasible?  That would be updated any time there's a new upload, and presumably the lookup would be pretty fast in those cases.

**Comment by marlo-longley** [comment]
@ggeisler @corylown Here's what I came up with for now - we are still only querying the last 30 days data, otherwise the query so slow it's not really useable. If an organization doesn't have any uploads from that period, they go to the bottom of the list. Thoughts on language / design for that?

![Screen Shot 2022-06-03 at 11 28 53](https://user-images.githubusercontent.com/1328900/171924828-f152b8f9-e86a-4ab1-86ef-6cfcbd282d2c.png)

**Comment by corylown** [comment]
@marlo-longley I think you could pretty easily get at least the last upload date for orgs that don't have any uploads in the past 30 days: `org.uploads.order(created_at: :desc).limit(1).created_at`

**Comment by ggeisler** [comment]
@marlo-longley @corylown I like the "No uploads in last 30 days" idea, if necessary (though hopefully from Cory's comment above it won't be).

I'm not sure about the sorting strategy. I might not have called it out specifically, but in all of the tickets related to the Activity tab tables, I've kept the sorting by **Provider** in the mockups. That was intentional. Since there's only one entry for each provider, I think it makes sense to retain the same order across the tabs (consistent with the Providers page table), so the user can quickly find the provider they're interested in, or compare providers quickly because they know where to expect a given provider's entry to be in the table.

**Comment by marlo-longley** [comment]
@ggeisler thanks ! I think sorting by provider on every tab is a great idea and simplifies things on my end. Sounds good.

**Comment by marlo-longley** [comment]
This is what we landed on. If no uploads in past thirty days, we indicate that in the last column.


![Screen Shot 2022-06-06 at 14 40 48](https://user-images.githubusercontent.com/1328900/172254961-8a5a3ec5-5d50-420e-92b4-77ddbaabe650.png)
