### ISSUE TITLE
OOM killer shuts down sidekiq on larger full and delta dump jobs

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#852]
Organizations missing full/delta dumps:

- [Chicago](https://pod.stanford.edu/organizations/chicago/streams/pod-sep-2021/normalized_data)
- [Cornell](https://pod.stanford.edu/organizations/cornell/streams/2022-05/normalized_data)
- [Duke](https://pod.stanford.edu/organizations/duke/streams/7546b907-2e75-4f8a-b13d-daf67d18b6cf/normalized_data)
- [Harvard](https://pod.stanford.edu/organizations/harvard/streams/20220204-with-items/normalized_data)
- [Princeton](https://pod.stanford.edu/organizations/princeton/streams/production/normalized_data)
- [Yale](https://pod.stanford.edu/organizations/yale/streams/2022-05-v1/normalized_data)

Sidekiq gets shutdown by OOM killer and jobs disappear.

From `/var/log/messages`

```
Jun  1 01:38:12 pod kernel: Out of memory: Kill process 26778 (ruby) score 392 or sacrifice child
Jun  1 01:38:12 pod kernel: Killed process 26778 (ruby), UID 503, total-vm:11024172kB, anon-rss:10420820kB, file-rss:0kB, shmem-rss:0kB
Jun  1 01:38:13 pod systemd: sidekiq-4.service: main process exited, code=killed, status=9/KILL
Jun  1 01:38:13 pod systemd: Unit sidekiq-4.service entered failed state.
Jun  1 01:38:13 pod systemd: sidekiq-4.service failed.
Jun  1 01:38:14 pod systemd: sidekiq-4.service holdoff time over, scheduling restart.
Jun  1 01:38:14 pod systemd: Stopped sidekiq.
Jun  1 01:38:14 pod systemd: Started sidekiq.
```

From `/var/log/sidekiq.log`

```
Jun  1 03:48:28 pod sidekiq: 2022-06-01T10:48:28.656Z pid=27092 tid=2edho class=GenerateDeltaDumpJob jid=439cab5b4f0945261af55e56 ERROR: Error performing GenerateDeltaDumpJob (Job ID: 7b3f60ab-cb3b-4778-8e7a-19d01fd5bdca) from Sidekiq(default) in 10126730.71ms: Sidekiq::Shutdown (Sidekiq::Shutdown):

```

**Comment by cbeer** [comment]
Is it because we're now chunking by 500 records instead of 100?

https://github.com/pod4lib/aggregator/blob/main/app/jobs/generate_full_dump_job.rb#L35

**Comment by thatbudakguy** [comment]
thoughts from pairing 6/1:
- try to set up a situation in staging where an organization has a high number of records (~6M) without a previous dump in order to reproduce the problem via large delta generation (@corylown is working on this)
- issue could be related to dump jobs using the database for marc records instead of files, which was a change that happened this workcycle
- both staging and prod have 24G of RAM, which is less than our stanford-provided dev machines. in the event we don't have further time to address this (likely), probably reasonable to ask ops to bump that up to 32G at least
- what's the impact of sidekiq settings on this? could we tweak `RAILS_MAX_THREADS` or sidekiq job count? see [prod config](https://github.com/sul-dlss/puppet/blob/4953c8cec101d1a18a5b18518eb6a65566f61ed3/hieradata/node/pod.stanford.edu.eyaml#L154-L157) and [staging config](https://github.com/sul-dlss/puppet/blob/4953c8cec101d1a18a5b18518eb6a65566f61ed3/hieradata/node/pod-stage.stanford.edu.eyaml#L157-L160) which actually differ in the job count

**Comment by corylown** [comment]
Appears to be resolved by increasing RAM on the VMs to 64GB and not trying to run all the full dump jobs at the same time.
