### ISSUE TITLE
Default stream being reset?

### ISSUE THREAD

**Issue by EJBivona** [pod4lib/aggregator#900]
I need to rework how Dartmouth's metadata submissions are handled, but in the mean time, I've suspended our contributions, and reset our default stream to be the one named 202206 twice.  Unfortunately, I've come back to aggregator twice, and found that the default stream has been reset to be 202207, which is damaged/limited, and should not be used.

I don't think my code is resetting the default stream (it hasn't run since 7/5), so I'm wondering what is (incorrectly) resetting Dartmouth's default stream, since I can't delete the damaged/limited stream 202207.

-Eric

**Comment by corylown** [comment]
@EJBivona We have a record of every change to the Stream model and I was able to track down the last time that stream 202207 (id: 428) was made the default:

```
 #<PaperTrail::Version:0x0000000008328a68
  id: 227941,
  item_type: "Stream",
  item_id: 428,
  event: "update",
  whodunnit: nil,
  object:
   "---\norganization_id: 13\ndefault: false\nid: 428\nname: '202207'\ncreated_at: !ruby/object:ActiveSupport::TimeWithZone\n  utc: 2022-07-02 04:17:27.585570000 Z\n  zone: &1 !ruby/object:ActiveSupport::TimeZone\n    name: Etc/UTC\n  time: 2022-07-02 04:17:27.585570000 Z\nupdated_at: !ruby/object:ActiveSupport::TimeWithZone\n  utc: 2022-07-21 13:06:55.000426000 Z\n  zone: *1\n  time: 2022-07-21 13:06:55.000426000 Z\nslug: '202207'\nstatus: active\n",
  created_at: Fri, 22 Jul 2022 15:47:16.869658000 UTC +00:00,
  object_changes:
   "---\ndefault:\n- false\n- true\nupdated_at:\n- !ruby/object:ActiveSupport::TimeWithZone\n  utc: 2022-07-21 13:06:55.000426000 Z\n  zone: &1 !ruby/object:ActiveSupport::TimeZone\n    name: Etc/UTC\n  time: 2022-07-21 13:06:55.000426000 Z\n- !ruby/object:ActiveSupport::TimeWithZone\n  utc: 2022-07-22 15:47:16.869658000 Z\n  zone: *1\n  time: 2022-07-22 15:47:16.869658000 Z\n">,
```

Since no user ID is associated with the change to the model (`whodunit: nil`), I know that the change was not initiated via the user interface. In the production logs from that date I see a `POST` request coming from IP `129.170.10.47` (which is affiliated with Dartmouth) to make Stream 202207 the default:

```
I, [2022-07-22T08:47:16.824849 #4105]  INFO -- : [a7b2de28-e1f3-444f-9958-b0239b2f5b41] Started POST "/organizations/dartmouth/streams/make_default?stream=202207" for 129.170.10.47 at 2022-07-22 08:47:16 -0700
```

The timestamp on the stream model change and the `make_default` request match, so as far as I can tell these requests to make stream 202207 the default are being initiated from Dartmouth, likely via a script or via curl using an access token.

**Comment by EJBivona** [comment]
@corylown, thanks for digging into this.  A very unintended consequence of an unfortunate CI/CD pipeline.  I'll work on clearing it up on my end.

-Eric
